- name: "setting time"
  command: "arch-chroot /mnt hwclock -u -w"
  
- name: "setting hostname"
  shell: "echo Co2BaseServer > /mnt/etc/hostname"
  
- name: "locale gen config"
  shell: "echo 'en_US.UTF-8 UTF-8' >> /mnt/etc/locale.gen"

- name: "locale gen"
  command: "arch-chroot /mnt locale-gen"

- name: "enable network"
  command: "arch-chroot /mnt systemctl enable dhcpcd.service"

- name: "enable network"
  command: "arch-chroot /mnt systemctl enable sshd"

- name: "creategrub"
  command: "arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB"

- name: "mkconfig"
  command: "arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg"

  #- name: "root passward setting"
  #shell: "arch-chroot /mnt echo root:{{root_password}}|chpasswd"
